### ISSUE TITLE
可以是可以，但是感觉好慢

### ISSUE THREAD

**Issue by idelin** [yokonsan/claude-in-slack-api#1]
有什么方式提升一下吗

**Comment by yokonsan** [comment]
得先明确是哪里慢，如果是claude自身回答慢，那就没办法

**Comment by yokonsan** [comment]
> 有什么方式提升一下吗


得先明确是哪里慢，如果是claude自身回答慢，那就没办法

**Comment by idelin** [comment]
不太好确认是哪个环节慢，毕竟也没拿到claude api 的权限，不过相较而言，比 chatgpt3.5 的回复慢多了

**Comment by yokonsan** [comment]
> 不太好确认是哪个环节慢，毕竟也没拿到claude api 的权限，不过相较而言，比 chatgpt3.5 的回复慢多了

是的，有空我看看能不能流式响应
