### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED  这个错误是token 错误导致的吗

### ISSUE THREAD

**Issue by everwind** [yokonsan/claude-in-slack-api#2]
raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host www.slack.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')]

**Comment by yokonsan** [comment]
> raise ClientConnectorCertificateError(req.connection_key, exc) from exc aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host [www.slack.com:443](http://www.slack.com:443) ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')]

请求方法加上 `ssl=False` 试试呢
