### ISSUE TITLE
用这种方式调用claude是不是容易被slack封停使用

### ISSUE THREAD

**Issue by starstar222** [yokonsan/claude-in-slack-api#6]
我的调用了半天后claude应用被封了

**Comment by yokonsan** [comment]
> 我的调用了半天后claude应用被封了

你的调用很频繁吗
我一直在用没有出现被封的情况

**Comment by suansuanchen** [comment]
slack，现在没办法添加claude了这也适用？

**Comment by yokonsan** [comment]
> slack，现在没办法添加claude了这也适用？

10分钟前我还在用
