### ISSUE TITLE
在Claude死机的情况下“清除上下文”的命令无效，Claude不响应。

### ISSUE THREAD

**Issue by sagehere** [yokonsan/claude-in-slack-api#7]
在Claude死机的情况下“清除上下文”的命令无效，Claude不响应。

![1](https://github.com/yokonsan/claude-in-slack-api/assets/107534793/247ab3b2-81e8-4e0a-93da-7994b8d2600d)

输入任何内容都是“typing...."
研究了一下，应该是要使用Slack中的 Slash 命令：/reset 就能重置救活，但单纯使用脚本'prompt':'/reset '是无效的。
希望作者能够改进“清除上下文”的功能。

**Comment by yokonsan** [comment]
这个typing是claude在处理上面的消息吧
/reset确实是正确的方式，但我没找到直接发送command的方式

**Comment by sagehere** [comment]
> 这个typing是claude在处理上面的消息吧 /reset确实是正确的方式，但我没找到直接发送command的方式

这个typing其实是死机了,长期一直是typing,若后续输入对话，后续对话返回也只有typing。只有登陆slack，在对话框里输入“/reset”才能重置。奇怪的地方是用脚本promt"/reset"是无效的，依旧typing...

**Comment by QinCaii** [comment]
哪儿都好，就是不能直接发送命令...

**Comment by bestK** [comment]
![image](https://github.com/yokonsan/claude-in-slack-api/assets/14979305/e7140acd-a525-4585-b539-e9a22d7e0922)

在 web 界面发送 `/reset` 命令，抓取如下请求即可

![image](https://github.com/yokonsan/claude-in-slack-api/assets/14979305/8c862f5e-4c6c-4118-935a-9ef5a0e856d0)


``` shell
curl --location --request POST 'https://jydhq.slack.com/api/chat.command' \
--header 'Cookie:  <your_slack_cookie>' \
--form 'token="xoxc-<your_claude_channel_token>"' \
--form 'command="/reset"' \
--form 'channel="<your_claude_channel>"'
```
