### ISSUE TITLE
一直报错 {'ok': False, 'error': 'cannot_dm_bot'}

### ISSUE THREAD

**Issue by Song345381185** [yokonsan/claude-in-slack-api#8]
slack_sdk.errors.SlackApiError: The request to the Slack API failed. (url: https://www.slack.com/api/conversations.open)
The server responded with: {'ok': False, 'error': 'cannot_dm_bot'}，所有都是按步骤来的

**Comment by yokonsan** [comment]
#4 
类似问题，参考下
